/******************************************************************************
 *                                                                            *
 * Player Progression System - XP, Levels, Achievements, Leaderboards         *
 *                                                                            *
 * Handles all player engagement systems including:                           *
 * - XP and leveling system                                                  *
 * - Achievement tracking and unlocking                                      *
 * - Daily login rewards and streaks                                         *
 * - Player titles/badges                                                    *
 * - Leaderboards                                                            *
 * - Progress notifications                                                  *
 * - Comparative statistics                                                  *
 *                                                                            *
 ******************************************************************************/

use spacetimedb::{Identity, Timestamp, ReducerContext, Table, SpacetimeType};
use log;

// Import table traits (auto-generated by SpacetimeDB)
use crate::player_progression::player_stats as PlayerStatsTableTrait;
use crate::player_progression::achievement_definition as AchievementDefinitionTableTrait;
use crate::player_progression::player_achievement as PlayerAchievementTableTrait;
use crate::player_progression::daily_login_reward as DailyLoginRewardTableTrait;
use crate::player_progression::achievement_unlock_notification as AchievementUnlockNotificationTableTrait;
use crate::player_progression::level_up_notification as LevelUpNotificationTableTrait;
use crate::player_progression::daily_login_notification as DailyLoginNotificationTableTrait;
use crate::player_progression::progress_notification as ProgressNotificationTableTrait;
use crate::player_progression::comparative_stat_notification as ComparativeStatNotificationTableTrait;
use crate::player_progression::leaderboard_entry as LeaderboardEntryTableTrait;
use crate::dropped_item::give_item_to_player_or_drop;
use crate::items::item_definition as ItemDefinitionTableTrait;
use crate::world_state::world_state as WorldStateTableTrait;
use crate::player as PlayerTableTrait;

// ============================================================================
// CONSTANTS
// ============================================================================

// XP Formula: 100 * level^1.5
pub fn xp_for_level(level: u32) -> u64 {
    (100.0 * (level as f64).powf(1.5)) as u64
}

/// Memory Shard reward formula for leveling up
/// Uses quadratic scaling: 5 + (level² / 10)
/// 
/// This provides:
/// - Level 1-10: 5-15 shards (small "top up" feeling)
/// - Level 25: ~67 shards
/// - Level 50: ~255 shards  
/// - Level 100: ~1,005 shards
/// - Total to level 100: ~34,300 shards (enough for full core memory grid)
///
/// The formula is designed to:
/// 1. Feel like a bonus, not a flood
/// 2. Scale meaningfully with progression
/// 3. Allow maxing core grid OR one faction path by level 100
pub fn shard_reward_for_level(level: u32) -> u64 {
    // Base 5 shards + quadratic scaling
    // This gives a nice curve that rewards higher levels substantially
    5 + ((level as u64 * level as u64) / 10)
}

// XP Sources (tuned for engagement)
pub const XP_FISH_CAUGHT: u64 = 10;
pub const XP_CAIRN_DISCOVERED: u64 = 50;
pub const XP_CONTRACT_COMPLETED: u64 = 25;
pub const XP_ITEM_CRAFTED: u64 = 5;
pub const XP_TREE_CHOPPED: u64 = 2;
pub const XP_STONE_MINED: u64 = 2;
pub const XP_ANIMAL_KILLED: u64 = 15;
pub const XP_APPARITION_BANISHED: u64 = 25;  // Hostile NPCs give more XP (dangerous combat)
pub const XP_SURVIVAL_MINUTE: u64 = 1;
pub const XP_CORAL_HARVESTED: u64 = 3;    // Underwater coral mining
pub const XP_PLANT_HARVESTED: u64 = 2;    // Picking wild plants/berries
pub const XP_CROP_HARVESTED: u64 = 1;     // Farming planted crops (slightly less)

// Progress notification thresholds (as percentages)
pub const PROGRESS_THRESHOLD_50: f32 = 0.5;
pub const PROGRESS_THRESHOLD_75: f32 = 0.75;
pub const PROGRESS_THRESHOLD_90: f32 = 0.9;

// ============================================================================
// HELPER FUNCTIONS FOR ACHIEVEMENT CHECKS
// ============================================================================

/// Count bits set in a specific range of a bitmask (inclusive start, inclusive end)
/// Used for category-based plant achievements
pub fn count_category_bits(bitmask: u64, start_bit: u32, end_bit: u32) -> u32 {
    let mut count = 0;
    for bit in start_bit..=end_bit {
        if (bitmask >> bit) & 1 == 1 {
            count += 1;
        }
    }
    count
}

// ============================================================================
// ENUMS
// ============================================================================

#[derive(SpacetimeType, Clone, Debug, PartialEq, Eq)]
pub enum AchievementCategory {
    Exploration,
    Combat,
    Crafting,
    Survival,
    Social,
    Collection,
}

#[derive(SpacetimeType, Clone, Debug, PartialEq, Eq)]
pub enum ProgressType {
    Level,
    Achievement,
    Contract,
    Cairn,
}

#[derive(SpacetimeType, Clone, Debug, PartialEq, Eq)]
pub enum LeaderboardCategory {
    ShardsEarned,
    LongestSurvival,
    ContractsCompleted,
    FishCaught,
    CairnsDiscovered,
    Level,
}

// ============================================================================
// TABLES
// ============================================================================

/// PlayerStats - XP, level, and aggregate tracking
#[spacetimedb::table(
    name = player_stats,
    public,
    index(name = idx_level, btree(columns = [level])),
    index(name = idx_total_shards, btree(columns = [total_shards_earned])),
    index(name = idx_survival_time, btree(columns = [longest_survival_seconds]))
)]
#[derive(Clone, Debug)]
pub struct PlayerStats {
    #[primary_key]
    pub player_id: Identity,
    pub total_xp: u64,
    pub level: u32,
    pub xp_to_next_level: u64,
    
    // Aggregate stats for achievements/leaderboards
    pub fish_caught: u32,
    pub animals_killed: u32,
    pub cairns_discovered: u32,
    pub contracts_completed: u32,
    pub items_crafted: u32,
    pub trees_chopped: u32,
    pub stones_mined: u32,
    pub corals_mined: u32,        // Underwater coral mining
    pub plants_harvested: u32,    // Foraging wild plants
    pub unique_fish_bitmask: u32, // Bitmask tracking unique fish types caught (bit 0 = Twigfish, etc.)
    pub unique_plant_bitmask: u64, // Bitmask tracking unique plant types harvested (64 bits for 58 plants)
    pub seeds_planted: u32,       // Count of seeds/crops planted by player
    pub deaths: u32,
    
    // Weapon-specific kill tracking
    pub bow_kills: u32,           // Kills with Hunting Bow
    pub crossbow_kills: u32,      // Kills with Crossbow
    pub gun_kills: u32,           // Kills with firearms (Makarov PM, PP-91 KEDR, etc.)
    pub harpoon_gun_kills: u32,   // Kills with Reed Harpoon Gun
    pub melee_kills: u32,         // All melee weapon kills
    pub spear_kills: u32,         // Kills with spears specifically
    
    // Taming tracking (specific achievement)
    pub walrus_tamed: bool,       // Has player tamed a walrus? (specific achievement)
    
    // Barrel/Loot tracking
    pub barrels_destroyed: u32,   // Total barrels destroyed/looted
    
    // Brewing tracking
    pub brews_completed: u32,     // Total successful brews
    
    // Shard Apparition tracking (Void manifestations - separate from regular animals)
    pub apparitions_banished: u32, // Total shard apparitions killed
    
    // Venom tracking (Cable Viper bites)
    pub venom_bites: u32,           // Total times bitten by Cable Vipers (venom effect applied)
    
    // Insanity tracking (for achievements)
    pub max_insanity_reached: f32,   // Highest insanity % ever reached (0.0-100.0)
    pub times_entrained: u32,        // How many times player reached 100% insanity (Entrainment)
    pub insanity_thresholds_crossed: u8, // Bitmask: bit 0=25%, bit 1=50%, bit 2=75%, bit 3=90%, bit 4=100%
    
    pub play_time_seconds: u64,
    pub longest_survival_seconds: u64,
    pub current_survival_start: Option<Timestamp>, // When current survival run started
    pub survival_quest_minutes_tracked: u32, // Minutes credited to daily survival quest (reset on death)
    pub total_shards_earned: u64,
    
    pub last_login_day: u32,        // For daily rewards (world day number)
    pub login_streak_days: u32,     // For streaks
    pub active_title_id: Option<String>,
    pub updated_at: Timestamp,
}

/// AchievementDefinition - seeded at init
#[spacetimedb::table(name = achievement_definition, public)]
#[derive(Clone, Debug)]
pub struct AchievementDefinition {
    #[primary_key]
    pub id: String,  // e.g., "first_cairn", "fish_100"
    pub name: String,
    pub description: String,
    pub icon: String,
    pub xp_reward: u64,
    pub title_reward: Option<String>,
    pub category: AchievementCategory,
}

/// PlayerAchievement - unlocked achievements per player
#[spacetimedb::table(
    name = player_achievement,
    public,
    index(name = idx_player_achievements, btree(columns = [player_id]))
)]
#[derive(Clone, Debug)]
pub struct PlayerAchievement {
    #[primary_key]
    #[auto_inc]
    pub id: u64,
    pub player_id: Identity,
    pub achievement_id: String,
    pub unlocked_at: Timestamp,
}

/// DailyLoginReward - reward tier definitions
#[spacetimedb::table(name = daily_login_reward, public)]
#[derive(Clone, Debug)]
pub struct DailyLoginReward {
    #[primary_key]
    pub day: u32,  // 1-7, then loops
    pub shard_reward: u64,
    pub bonus_xp: u64,
}

/// AchievementUnlockNotification - sent to client for toast notifications
#[spacetimedb::table(name = achievement_unlock_notification, public)]
#[derive(Clone, Debug)]
pub struct AchievementUnlockNotification {
    #[primary_key]
    #[auto_inc]
    pub id: u64,
    pub player_id: Identity,
    pub achievement_id: String,
    pub achievement_name: String,
    pub xp_awarded: u64,
    pub title_awarded: Option<String>,
    pub unlocked_at: Timestamp,
}

/// LevelUpNotification - sent to client when player levels up
#[spacetimedb::table(name = level_up_notification, public)]
#[derive(Clone, Debug)]
pub struct LevelUpNotification {
    #[primary_key]
    #[auto_inc]
    pub id: u64,
    pub player_id: Identity,
    pub new_level: u32,
    pub xp_awarded: u64,
    pub shards_awarded: u64,  // Memory Shards granted for this level up
    pub unlocked_at: Timestamp,
}

/// DailyLoginNotification - sent to client for daily reward display
#[spacetimedb::table(
    name = daily_login_notification,
    public,
    index(name = idx_player_daily, btree(columns = [player_id]))
)]
#[derive(Clone, Debug)]
pub struct DailyLoginNotification {
    #[primary_key]
    #[auto_inc]
    pub id: u64,
    pub player_id: Identity,
    pub day: u32,
    pub shard_reward: u64,
    pub bonus_xp: u64,
    pub streak_days: u32,
    pub unlocked_at: Timestamp,
}

/// ProgressNotification - threshold-based progress updates
#[spacetimedb::table(
    name = progress_notification,
    public,
    index(name = idx_player_progress, btree(columns = [player_id]))
)]
#[derive(Clone, Debug)]
pub struct ProgressNotification {
    #[primary_key]
    #[auto_inc]
    pub id: u64,
    pub player_id: Identity,
    pub message: String,
    pub progress_type: ProgressType,
    pub current_value: u64,
    pub target_value: u64,
    pub progress_percent: f32,
    pub created_at: Timestamp,
}

/// ComparativeStatNotification - percentile-based stats on death
#[spacetimedb::table(name = comparative_stat_notification, public)]
#[derive(Clone, Debug)]
pub struct ComparativeStatNotification {
    #[primary_key]
    #[auto_inc]
    pub id: u64,
    pub player_id: Identity,
    pub stat_name: String,
    pub player_value: u64,
    pub percentile: f32,
    pub message: String,
    pub created_at: Timestamp,
}

/// LeaderboardEntry - computed leaderboard entries
#[spacetimedb::table(
    name = leaderboard_entry,
    public,
    index(name = idx_category_rank, btree(columns = [category, rank]))
)]
#[derive(Clone, Debug)]
pub struct LeaderboardEntry {
    #[primary_key]
    #[auto_inc]
    pub id: u64,
    pub category: LeaderboardCategory,
    pub rank: u32,
    pub player_id: Identity,
    pub player_username: String,
    pub value: u64,
    pub updated_at: Timestamp,
}

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/// Initialize or get PlayerStats for a player
pub fn get_or_init_player_stats(ctx: &ReducerContext, player_id: Identity) -> PlayerStats {
    let stats_table = ctx.db.player_stats();
    
    if let Some(stats) = stats_table.player_id().find(&player_id) {
        return stats.clone();
    }
    
    // Initialize new player stats
    let new_stats = PlayerStats {
        player_id,
        total_xp: 0,
        level: 1,
        xp_to_next_level: xp_for_level(1),
        fish_caught: 0,
        animals_killed: 0,
        cairns_discovered: 0,
        contracts_completed: 0,
        items_crafted: 0,
        trees_chopped: 0,
        stones_mined: 0,
        corals_mined: 0,
        plants_harvested: 0,
        unique_fish_bitmask: 0,
        unique_plant_bitmask: 0,
        seeds_planted: 0,
        deaths: 0,
        bow_kills: 0,
        crossbow_kills: 0,
        gun_kills: 0,
        harpoon_gun_kills: 0,
        melee_kills: 0,
        spear_kills: 0,
        walrus_tamed: false,
        barrels_destroyed: 0,
        brews_completed: 0,
        apparitions_banished: 0,
        venom_bites: 0,
        max_insanity_reached: 0.0,
        times_entrained: 0,
        insanity_thresholds_crossed: 0,
        play_time_seconds: 0,
        longest_survival_seconds: 0,
        current_survival_start: Some(ctx.timestamp),
        survival_quest_minutes_tracked: 0,
        total_shards_earned: 0,
        last_login_day: 0,
        login_streak_days: 0,
        active_title_id: None,
        updated_at: ctx.timestamp,
    };
    
    stats_table.insert(new_stats.clone());
    log::info!("Initialized PlayerStats for player {}", player_id);
    
    new_stats
}

/// Award XP to a player and check for level ups
pub fn award_xp(ctx: &ReducerContext, player_id: Identity, xp_amount: u64) -> Result<(), String> {
    let stats_table = ctx.db.player_stats();
    let mut stats = get_or_init_player_stats(ctx, player_id);
    
    let old_level = stats.level;
    stats.total_xp += xp_amount;
    stats.updated_at = ctx.timestamp;
    
    // Check for level up
    let mut new_level = stats.level;
    loop {
        let xp_needed_for_next = xp_for_level(new_level + 1);
        if stats.total_xp >= xp_needed_for_next {
            new_level += 1;
        } else {
            break;
        }
    }
    
    stats.level = new_level;
    stats.xp_to_next_level = if new_level > 0 {
        xp_for_level(new_level + 1)
    } else {
        xp_for_level(1)
    };
    
    // Send level up notification if leveled up
    if new_level > old_level {
        // Calculate total shards for all levels gained (handles multi-level jumps)
        let mut total_shards_earned = 0u64;
        for level in (old_level + 1)..=new_level {
            total_shards_earned += shard_reward_for_level(level);
        }
        
        // Update total shards earned in stats
        stats.total_shards_earned += total_shards_earned;
        
        // Award Memory Shards to player
        if total_shards_earned > 0 {
            // Find Memory Shard item definition
            let memory_shard_def_id = ctx.db.item_definition().iter()
                .find(|def| def.name == "Memory Shard")
                .map(|def| def.id);
            
            if let Some(shard_def_id) = memory_shard_def_id {
                // Give shards - will drop at feet if inventory full
                match give_item_to_player_or_drop(ctx, player_id, shard_def_id, total_shards_earned as u32) {
                    Ok(added_to_inv) => {
                        if added_to_inv {
                            log::info!("🎉 Player {} leveled up to {}! Awarded {} Memory Shards to inventory", 
                                player_id, new_level, total_shards_earned);
                        } else {
                            log::info!("🎉 Player {} leveled up to {}! Dropped {} Memory Shards at feet (inventory full)", 
                                player_id, new_level, total_shards_earned);
                        }
                    }
                    Err(e) => {
                        log::error!("Failed to award level-up Memory Shards to player {}: {}", player_id, e);
                    }
                }
            } else {
                log::error!("Memory Shard item definition not found! Cannot award level-up shards.");
            }
        }
        
        // Create notification with shards info
        let level_up_notif = LevelUpNotification {
            id: 0,
            player_id,
            new_level,
            xp_awarded: xp_amount,
            shards_awarded: total_shards_earned,
            unlocked_at: ctx.timestamp,
        };
        ctx.db.level_up_notification().insert(level_up_notif);
        log::info!("Player {} leveled up to level {}! (+{} shards)", player_id, new_level, total_shards_earned);
        
        // Check for level-based achievements
        check_level_achievements(ctx, player_id, new_level)?;
    }
    
    // Update stats (moved after shard calculation to include updated total_shards_earned)
    stats_table.player_id().update(stats.clone());
    
    // Check progress notifications
    check_progress_notifications(ctx, player_id, &stats)?;
    
    Ok(())
}

/// Track a stat increment and check for achievements
/// This is the overloaded version that increments a stat before checking
pub fn track_stat_and_check_achievements(
    ctx: &ReducerContext,
    player_id: Identity,
    stat_type: &str,
    amount: u64,
) -> Result<(), String> {
    let stats_table = ctx.db.player_stats();
    let mut stats = get_or_init_player_stats(ctx, player_id);
    
    // Increment the appropriate stat
    match stat_type {
        "fish_caught" => stats.fish_caught += amount as u32,
        "animals_killed" => stats.animals_killed += amount as u32,
        "cairns_discovered" => stats.cairns_discovered += amount as u32,
        "contracts_completed" => stats.contracts_completed += amount as u32,
        "items_crafted" => stats.items_crafted += amount as u32,
        "trees_chopped" => stats.trees_chopped += amount as u32,
        "stones_mined" => stats.stones_mined += amount as u32,
        "corals_mined" => stats.corals_mined += amount as u32,
        "plants_harvested" => stats.plants_harvested += amount as u32,
        "seeds_planted" => stats.seeds_planted += amount as u32,
        "deaths" => stats.deaths += amount as u32,
        // Weapon-specific kills
        "bow_kills" => stats.bow_kills += amount as u32,
        "crossbow_kills" => stats.crossbow_kills += amount as u32,
        "gun_kills" => stats.gun_kills += amount as u32,
        "harpoon_gun_kills" => stats.harpoon_gun_kills += amount as u32,
        "melee_kills" => stats.melee_kills += amount as u32,
        "spear_kills" => stats.spear_kills += amount as u32,
        // Barrel/Loot
        "barrels_destroyed" => stats.barrels_destroyed += amount as u32,
        // Brewing
        "brews_completed" => stats.brews_completed += amount as u32,
        // Shard Apparitions (Void manifestations)
        "apparitions_banished" => stats.apparitions_banished += amount as u32,
        // Venom bites (Cable Viper attacks)
        "venom_bites" => stats.venom_bites += amount as u32,
        // Walrus taming (boolean, set to true if any amount)
        "walrus_tamed" => stats.walrus_tamed = true,
        _ => {
            log::warn!("Unknown stat type: {}", stat_type);
            return Ok(());
        }
    }
    
    stats.updated_at = ctx.timestamp;
    stats_table.player_id().update(stats);
    
    // Now check achievements
    check_achievements(ctx, player_id)
}

/// Check and unlock achievements based on stats
pub fn check_achievements(ctx: &ReducerContext, player_id: Identity) -> Result<(), String> {
    let stats = get_or_init_player_stats(ctx, player_id);
    let achievement_defs = ctx.db.achievement_definition();
    let player_achievements = ctx.db.player_achievement();
    
    // Get already unlocked achievement IDs
    let unlocked_ids: Vec<String> = player_achievements
        .idx_player_achievements()
        .filter(&player_id)
        .map(|a| a.achievement_id.clone())
        .collect();
    
    // Check each achievement definition
    for achievement_def in achievement_defs.iter() {
        // Skip if already unlocked
        if unlocked_ids.contains(&achievement_def.id) {
            continue;
        }
        
        // Check if achievement conditions are met
        let should_unlock = match achievement_def.id.as_str() {
            // Cairn/Exploration achievements
            "first_cairn" => stats.cairns_discovered >= 1,
            "cairn_5" => stats.cairns_discovered >= 5,
            "cairn_hunter" => stats.cairns_discovered >= 10,
            "cairn_all" => stats.cairns_discovered >= 14,
            
            // Fishing achievements (tiered progression)
            "fish_10" => stats.fish_caught >= 10,
            "fish_25" => stats.fish_caught >= 25,
            "fish_50" => stats.fish_caught >= 50,
            "fish_100" => stats.fish_caught >= 100,
            "fish_250" => stats.fish_caught >= 250,
            "fish_500" => stats.fish_caught >= 500,
            
            // Fish variety achievements (unique types caught)
            "fish_types_3" => (stats.unique_fish_bitmask.count_ones()) >= 3,
            "fish_types_8" => (stats.unique_fish_bitmask.count_ones()) >= 8,
            "fish_types_12" => (stats.unique_fish_bitmask.count_ones()) >= 12,
            "fish_types_16" => (stats.unique_fish_bitmask.count_ones()) >= 16,
            
            // Coral/Diving achievements (tiered progression)
            "coral_10" => stats.corals_mined >= 10,
            "coral_25" => stats.corals_mined >= 25,
            "coral_50" => stats.corals_mined >= 50,
            "coral_100" => stats.corals_mined >= 100,
            
            // Plant/Foraging achievements (tiered progression)
            "plants_50" => stats.plants_harvested >= 50,
            "plants_100" => stats.plants_harvested >= 100,
            "plants_250" => stats.plants_harvested >= 250,
            "plants_500" => stats.plants_harvested >= 500,
            
            // Plant variety achievements (unique types harvested - uses 64-bit bitmask)
            "plant_types_5" => (stats.unique_plant_bitmask.count_ones()) >= 5,
            "plant_types_15" => (stats.unique_plant_bitmask.count_ones()) >= 15,
            "plant_types_30" => (stats.unique_plant_bitmask.count_ones()) >= 30,
            "plant_types_49" => (stats.unique_plant_bitmask.count_ones()) >= 49,
            
            // Category completion achievements (specific bitmask ranges)
            // Berry category: bits 0-6 (7 types)
            "berry_collector" => count_category_bits(stats.unique_plant_bitmask, 0, 6) >= 7,
            // Mushroom category: bits 7-12 (6 types)
            "mushroom_master" => count_category_bits(stats.unique_plant_bitmask, 7, 12) >= 6,
            // Herb category: bits 13-21 (9 types)
            "herb_master" => count_category_bits(stats.unique_plant_bitmask, 13, 21) >= 9,
            // Toxic category: bits 22-26 (5 types)
            "toxic_expert" => count_category_bits(stats.unique_plant_bitmask, 22, 26) >= 5,
            // Arctic category: bits 27-32 (6 types)
            "arctic_botanist" => count_category_bits(stats.unique_plant_bitmask, 27, 32) >= 6,
            // Vegetable category: bits 33-40 (8 types)
            "vegetable_farmer" => count_category_bits(stats.unique_plant_bitmask, 33, 40) >= 8,
            // Fiber category: bits 41-48 (8 types)
            "fiber_gatherer" => count_category_bits(stats.unique_plant_bitmask, 41, 48) >= 8,
            
            // Farming achievements (seeds planted)
            "farmer_10" => stats.seeds_planted >= 10,
            "farmer_50" => stats.seeds_planted >= 50,
            "farmer_100" => stats.seeds_planted >= 100,
            "farmer_250" => stats.seeds_planted >= 250,
            
            // Combat achievements (tiered progression)
            "animals_10" => stats.animals_killed >= 10,
            "animals_25" => stats.animals_killed >= 25,
            "animals_50" => stats.animals_killed >= 50,
            "animals_100" => stats.animals_killed >= 100,
            
            // Resource gathering achievements (tiered progression)
            "trees_100" => stats.trees_chopped >= 100,
            "trees_250" => stats.trees_chopped >= 250,
            "trees_500" => stats.trees_chopped >= 500,
            "trees_1000" => stats.trees_chopped >= 1000,
            "stones_100" => stats.stones_mined >= 100,
            "stones_250" => stats.stones_mined >= 250,
            "stones_500" => stats.stones_mined >= 500,
            "stones_1000" => stats.stones_mined >= 1000,
            
            // Crafting achievements (tiered progression)
            "crafted_50" => stats.items_crafted >= 50,
            "crafted_100" => stats.items_crafted >= 100,
            "crafted_250" => stats.items_crafted >= 250,
            "crafted_500" => stats.items_crafted >= 500,
            
            // Survival time achievements (tiered progression)
            "survivor_1h" => stats.longest_survival_seconds >= 3600,
            "survivor_6h" => stats.longest_survival_seconds >= 21600,
            "survivor_12h" => stats.longest_survival_seconds >= 43200,
            "survivor_24h" => stats.longest_survival_seconds >= 86400,
            
            // Login streak achievements
            "login_7" => stats.login_streak_days >= 7,
            "login_30" => stats.login_streak_days >= 30,
            
            // Contract achievements
            "contracts_10" => stats.contracts_completed >= 10,
            "contracts_50" => stats.contracts_completed >= 50,
            "contracts_100" => stats.contracts_completed >= 100,
            
            // Level achievements  
            "level_10" => stats.level >= 10,
            "level_25" => stats.level >= 25,
            "level_50" => stats.level >= 50,
            "level_100" => stats.level >= 100,
            
            // Death achievements (tiered progression)
            "first_death" => stats.deaths >= 1,
            "deaths_10" => stats.deaths >= 10,
            "deaths_50" => stats.deaths >= 50,
            "deaths_100" => stats.deaths >= 100,
            
            // === "FIRST" MILESTONE ACHIEVEMENTS ===
            // These reward players for their first action in each category
            "first_fish" => stats.fish_caught >= 1,
            "first_kill" => stats.animals_killed >= 1,
            "first_plant" => stats.plants_harvested >= 1,
            "first_tree" => stats.trees_chopped >= 1,
            "first_stone" => stats.stones_mined >= 1,
            "first_seed" => stats.seeds_planted >= 1,
            "first_craft" => stats.items_crafted >= 1,
            "first_coral" => stats.corals_mined >= 1,
            "first_brew" => stats.brews_completed >= 1,
            "first_barrel" => stats.barrels_destroyed >= 1,
            
            // === WEAPON-SPECIFIC KILL ACHIEVEMENTS ===
            // Ranged weapons
            "bow_kills_10" => stats.bow_kills >= 10,
            "bow_kills_50" => stats.bow_kills >= 50,
            "bow_kills_100" => stats.bow_kills >= 100,
            "crossbow_kills_10" => stats.crossbow_kills >= 10,
            "crossbow_kills_50" => stats.crossbow_kills >= 50,
            "crossbow_kills_100" => stats.crossbow_kills >= 100,
            "gun_kills_10" => stats.gun_kills >= 10,
            "gun_kills_50" => stats.gun_kills >= 50,
            "gun_kills_100" => stats.gun_kills >= 100,
            // Harpoon Gun
            "harpoon_gun_kills_10" => stats.harpoon_gun_kills >= 10,
            "harpoon_gun_kills_50" => stats.harpoon_gun_kills >= 50,
            "harpoon_gun_kills_100" => stats.harpoon_gun_kills >= 100,
            // Melee weapons
            "melee_kills_10" => stats.melee_kills >= 10,
            "melee_kills_50" => stats.melee_kills >= 50,
            "melee_kills_100" => stats.melee_kills >= 100,
            "spear_kills_25" => stats.spear_kills >= 25,
            "spear_kills_100" => stats.spear_kills >= 100,
            
            // === TAMING ACHIEVEMENT (Specific) ===
            "walrus_tamer" => stats.walrus_tamed,
            
            // === BARREL ACHIEVEMENTS ===
            "barrels_10" => stats.barrels_destroyed >= 10,
            "barrels_50" => stats.barrels_destroyed >= 50,
            "barrels_100" => stats.barrels_destroyed >= 100,
            
            // === BREWING ACHIEVEMENTS ===
            "brews_5" => stats.brews_completed >= 5,
            "brews_25" => stats.brews_completed >= 25,
            "brews_100" => stats.brews_completed >= 100,
            
            // === SHARD APPARITION / VOID MANIFESTATION ACHIEVEMENTS ===
            "first_banishment" => stats.apparitions_banished >= 1,
            "apparitions_10" => stats.apparitions_banished >= 10,
            "apparitions_25" => stats.apparitions_banished >= 25,
            "apparitions_50" => stats.apparitions_banished >= 50,
            "apparitions_100" => stats.apparitions_banished >= 100,
            "apparitions_250" => stats.apparitions_banished >= 250,
            "apparitions_500" => stats.apparitions_banished >= 500,
            "apparitions_1000" => stats.apparitions_banished >= 1000,
            
            // === VENOM BITE ACHIEVEMENTS (Cable Viper attacks) ===
            "first_venom_bite" => stats.venom_bites >= 1,
            "venom_bites_5" => stats.venom_bites >= 5,
            "venom_bites_10" => stats.venom_bites >= 10,
            "venom_bites_25" => stats.venom_bites >= 25,
            "venom_bites_50" => stats.venom_bites >= 50,
            
            // === INSANITY / SOVA ACHIEVEMENTS ===
            // Threshold-based (uses bitmask: bit 0=25%, bit 1=50%, bit 2=75%, bit 3=90%, bit 4=100%)
            "insanity_25" => (stats.insanity_thresholds_crossed & 0b00001) != 0,  // bit 0
            "insanity_50" => (stats.insanity_thresholds_crossed & 0b00010) != 0,  // bit 1
            "insanity_75" => (stats.insanity_thresholds_crossed & 0b00100) != 0,  // bit 2
            "insanity_90" => (stats.insanity_thresholds_crossed & 0b01000) != 0,  // bit 3
            "insanity_100" => (stats.insanity_thresholds_crossed & 0b10000) != 0, // bit 4 (also times_entrained >= 1)
            // Entrainment count achievements
            "entrainment_5" => stats.times_entrained >= 5,
            "entrainment_10" => stats.times_entrained >= 10,
            "entrainment_25" => stats.times_entrained >= 25,
            
            // Shard achievements
            "shards_1000" => stats.total_shards_earned >= 1000,
            "shards_10000" => stats.total_shards_earned >= 10000,
            
            _ => false,
        };
        
        if should_unlock {
            unlock_achievement(ctx, player_id, &achievement_def)?;
        }
    }
    
    Ok(())
}

/// Unlock a specific achievement
fn unlock_achievement(
    ctx: &ReducerContext,
    player_id: Identity,
    achievement_def: &AchievementDefinition,
) -> Result<(), String> {
    // Check if already unlocked
    let already_unlocked = ctx.db.player_achievement()
        .idx_player_achievements()
        .filter(&player_id)
        .any(|a| a.achievement_id == achievement_def.id);
    
    if already_unlocked {
        return Ok(());
    }
    
    // Record achievement unlock
    ctx.db.player_achievement().insert(PlayerAchievement {
        id: 0,
        player_id,
        achievement_id: achievement_def.id.clone(),
        unlocked_at: ctx.timestamp,
    });
    
    // Award XP
    if achievement_def.xp_reward > 0 {
        award_xp(ctx, player_id, achievement_def.xp_reward)?;
    }
    
    // Send notification
    let notif = AchievementUnlockNotification {
        id: 0,
        player_id,
        achievement_id: achievement_def.id.clone(),
        achievement_name: achievement_def.name.clone(),
        xp_awarded: achievement_def.xp_reward,
        title_awarded: achievement_def.title_reward.clone(),
        unlocked_at: ctx.timestamp,
    };
    ctx.db.achievement_unlock_notification().insert(notif);
    
    // If title reward, make it available (but don't auto-equip)
    // Titles are managed separately via set_active_title reducer
    
    log::info!("Achievement unlocked: {} for player {}", achievement_def.name, player_id);
    
    Ok(())
}

/// Check level-based achievements
fn check_level_achievements(ctx: &ReducerContext, player_id: Identity, level: u32) -> Result<(), String> {
    check_achievements(ctx, player_id)
}

/// Track insanity threshold crossing and check for achievements
/// Called from player_stats.rs when a player crosses an insanity threshold
/// 
/// Arguments:
/// - `threshold`: The insanity threshold that was crossed (25.0, 50.0, 75.0, 90.0, or 100.0)
/// - `current_insanity`: The player's current insanity value
pub fn track_insanity_threshold(
    ctx: &ReducerContext,
    player_id: Identity,
    threshold: f32,
    current_insanity: f32,
) -> Result<(), String> {
    let stats_table = ctx.db.player_stats();
    let mut stats = get_or_init_player_stats(ctx, player_id);
    
    // Update max insanity if this is higher
    if current_insanity > stats.max_insanity_reached {
        stats.max_insanity_reached = current_insanity;
    }
    
    // Set the appropriate bit in the bitmask based on threshold
    // bit 0=25%, bit 1=50%, bit 2=75%, bit 3=90%, bit 4=100%
    let bit_to_set = match threshold as u32 {
        25 => 0b00001,  // bit 0
        50 => 0b00010,  // bit 1
        75 => 0b00100,  // bit 2
        90 => 0b01000,  // bit 3
        100 => {
            // Reaching 100% (Entrainment) - increment counter and set bit
            stats.times_entrained += 1;
            log::info!("Player {} experienced Entrainment! Total count: {}", player_id, stats.times_entrained);
            0b10000  // bit 4
        },
        _ => {
            log::warn!("Unknown insanity threshold: {}", threshold);
            0
        }
    };
    
    // Set the bit (idempotent operation - can call multiple times safely)
    stats.insanity_thresholds_crossed |= bit_to_set;
    stats.updated_at = ctx.timestamp;
    
    // Update stats
    stats_table.player_id().update(stats);
    
    // Check for newly unlocked achievements
    check_achievements(ctx, player_id)?;
    
    Ok(())
}

/// Check progress notifications (50%, 75%, 90% thresholds)
fn check_progress_notifications(
    ctx: &ReducerContext,
    player_id: Identity,
    stats: &PlayerStats,
) -> Result<(), String> {
    let current_xp = stats.total_xp;
    let xp_for_current_level = if stats.level > 1 {
        xp_for_level(stats.level)
    } else {
        0
    };
    let xp_for_next_level = stats.xp_to_next_level;
    let xp_in_current_level = current_xp.saturating_sub(xp_for_current_level);
    let xp_needed_for_next = xp_for_next_level.saturating_sub(xp_for_current_level);
    
    if xp_needed_for_next == 0 {
        return Ok(());
    }
    
    let progress = xp_in_current_level as f32 / xp_needed_for_next as f32;
    
    // Check thresholds (only send once per threshold)
    let last_notif = ctx.db.progress_notification()
        .idx_player_progress()
        .filter(&player_id)
        .max_by(|a, b| a.created_at.cmp(&b.created_at));
    
    let last_threshold = if let Some(notif) = last_notif {
        notif.progress_percent
    } else {
        0.0
    };
    
    let threshold_to_check = if progress >= PROGRESS_THRESHOLD_90 && last_threshold < PROGRESS_THRESHOLD_90 {
        Some((PROGRESS_THRESHOLD_90, "90% to next level!"))
    } else if progress >= PROGRESS_THRESHOLD_75 && last_threshold < PROGRESS_THRESHOLD_75 {
        Some((PROGRESS_THRESHOLD_75, "75% to next level!"))
    } else if progress >= PROGRESS_THRESHOLD_50 && last_threshold < PROGRESS_THRESHOLD_50 {
        Some((PROGRESS_THRESHOLD_50, "50% to next level!"))
    } else {
        None
    };
    
    if let Some((threshold, message)) = threshold_to_check {
        let notif = ProgressNotification {
            id: 0,
            player_id,
            message: message.to_string(),
            progress_type: ProgressType::Level,
            current_value: xp_in_current_level,
            target_value: xp_needed_for_next,
            progress_percent: threshold,
            created_at: ctx.timestamp,
        };
        ctx.db.progress_notification().insert(notif);
    }
    
    Ok(())
}

/// Calculate percentile for a value in a distribution
pub fn calculate_percentile(value: u64, all_values: &[u64]) -> f32 {
    if all_values.is_empty() {
        return 0.0;
    }
    
    let mut sorted = all_values.to_vec();
    sorted.sort();
    
    let count_below = sorted.iter().filter(|&&v| v < value).count();
    let count_equal = sorted.iter().filter(|&&v| v == value).count();
    
    // Percentile = (count_below + 0.5 * count_equal) / total
    let percentile = (count_below as f32 + 0.5 * count_equal as f32) / sorted.len() as f32;
    percentile * 100.0 // Return as percentage (0-100)
}

/// Initialize achievement definitions (called in init_module)
pub fn seed_achievements(ctx: &ReducerContext) -> Result<(), String> {
    let achievement_table = ctx.db.achievement_definition();
    
    // Check if already seeded
    if achievement_table.iter().count() > 0 {
        log::debug!("Achievement definitions already seeded");
        return Ok(());
    }
    
    let achievements = vec![
        AchievementDefinition {
            id: "first_cairn".to_string(),
            name: "Curious Explorer".to_string(),
            description: "Discover your first cairn".to_string(),
            icon: "🗿".to_string(),
            xp_reward: 50,
            title_reward: None,
            category: AchievementCategory::Exploration,
        },
        AchievementDefinition {
            id: "cairn_hunter".to_string(),
            name: "Lore Keeper".to_string(),
            description: "Discover 10 cairns".to_string(),
            icon: "📚".to_string(),
            xp_reward: 200,
            title_reward: Some("Lore Keeper".to_string()),
            category: AchievementCategory::Exploration,
        },
        AchievementDefinition {
            id: "fish_10".to_string(),
            name: "Novice Angler".to_string(),
            description: "Catch 10 fish".to_string(),
            icon: "🎣".to_string(),
            xp_reward: 50,
            title_reward: None,
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "fish_25".to_string(),
            name: "Hobbyist Angler".to_string(),
            description: "Catch 25 fish".to_string(),
            icon: "🎣".to_string(),
            xp_reward: 75,
            title_reward: None,
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "fish_50".to_string(),
            name: "Skilled Angler".to_string(),
            description: "Catch 50 fish".to_string(),
            icon: "🎣".to_string(),
            xp_reward: 100,
            title_reward: None,
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "fish_100".to_string(),
            name: "Master Angler".to_string(),
            description: "Catch 100 fish".to_string(),
            icon: "🐟".to_string(),
            xp_reward: 300,
            title_reward: Some("Master Angler".to_string()),
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "fish_250".to_string(),
            name: "Seasoned Fisher".to_string(),
            description: "Catch 250 fish - the sea provides".to_string(),
            icon: "🐟".to_string(),
            xp_reward: 400,
            title_reward: None,
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "fish_500".to_string(),
            name: "Lord of the Bering".to_string(),
            description: "Catch 500 fish - master the frigid waters".to_string(),
            icon: "🦈".to_string(),
            xp_reward: 600,
            title_reward: Some("Lord of the Bering".to_string()),
            category: AchievementCategory::Collection,
        },
        // Fish variety achievements (unique types)
        AchievementDefinition {
            id: "fish_types_3".to_string(),
            name: "Variety Sampler".to_string(),
            description: "Catch 3 different types of fish".to_string(),
            icon: "🐠".to_string(),
            xp_reward: 50,
            title_reward: None,
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "fish_types_8".to_string(),
            name: "Diverse Angler".to_string(),
            description: "Catch 8 different types of fish".to_string(),
            icon: "🐡".to_string(),
            xp_reward: 150,
            title_reward: None,
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "fish_types_12".to_string(),
            name: "Fish Connoisseur".to_string(),
            description: "Catch 12 different types of fish".to_string(),
            icon: "🎏".to_string(),
            xp_reward: 300,
            title_reward: Some("Fish Connoisseur".to_string()),
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "fish_types_16".to_string(),
            name: "Complete Ichthyologist".to_string(),
            description: "Catch all 16 fish types - catalog the Bering Sea".to_string(),
            icon: "📖".to_string(),
            xp_reward: 500,
            title_reward: Some("Ichthyologist".to_string()),
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "survivor_1h".to_string(),
            name: "Survivor".to_string(),
            description: "Survive for 1 hour".to_string(),
            icon: "⏱️".to_string(),
            xp_reward: 100,
            title_reward: None,
            category: AchievementCategory::Survival,
        },
        AchievementDefinition {
            id: "survivor_6h".to_string(),
            name: "Enduring".to_string(),
            description: "Survive for 6 hours".to_string(),
            icon: "⏰".to_string(),
            xp_reward: 200,
            title_reward: Some("Enduring".to_string()),
            category: AchievementCategory::Survival,
        },
        AchievementDefinition {
            id: "survivor_12h".to_string(),
            name: "Hardened".to_string(),
            description: "Survive for 12 hours".to_string(),
            icon: "💪".to_string(),
            xp_reward: 350,
            title_reward: Some("Hardened".to_string()),
            category: AchievementCategory::Survival,
        },
        AchievementDefinition {
            id: "survivor_24h".to_string(),
            name: "Veteran".to_string(),
            description: "Survive for 24 hours".to_string(),
            icon: "🏆".to_string(),
            xp_reward: 500,
            title_reward: Some("Veteran".to_string()),
            category: AchievementCategory::Survival,
        },
        AchievementDefinition {
            id: "contracts_10".to_string(),
            name: "Contractor".to_string(),
            description: "Complete 10 ALK contracts".to_string(),
            icon: "📋".to_string(),
            xp_reward: 150,
            title_reward: None,
            category: AchievementCategory::Social,
        },
        AchievementDefinition {
            id: "contracts_50".to_string(),
            name: "ALK Elite".to_string(),
            description: "Complete 50 ALK contracts".to_string(),
            icon: "⭐".to_string(),
            xp_reward: 400,
            title_reward: Some("ALK Elite".to_string()),
            category: AchievementCategory::Social,
        },
        AchievementDefinition {
            id: "first_death".to_string(),
            name: "Learning Experience".to_string(),
            description: "Die for the first time".to_string(),
            icon: "💀".to_string(),
            xp_reward: 10,
            title_reward: None,
            category: AchievementCategory::Survival,
        },
        AchievementDefinition {
            id: "level_10".to_string(),
            name: "Rising Star".to_string(),
            description: "Reach level 10".to_string(),
            icon: "⭐".to_string(),
            xp_reward: 200,
            title_reward: None,
            category: AchievementCategory::Survival,
        },
        AchievementDefinition {
            id: "level_25".to_string(),
            name: "Established".to_string(),
            description: "Reach level 25".to_string(),
            icon: "🌟".to_string(),
            xp_reward: 500,
            title_reward: Some("Established".to_string()),
            category: AchievementCategory::Survival,
        },
        // === LORE-THEMED ACHIEVEMENTS ===
        // Based on the game's world: Bering Sea, ALK Compound, Aleut culture, volcanic island
        
        // Cairn Lore Discoveries (themed around the narrative)
        AchievementDefinition {
            id: "cairn_all".to_string(),
            name: "Truth Seeker".to_string(),
            description: "Discover all 14 cairns and uncover the island's secrets".to_string(),
            icon: "📖".to_string(),
            xp_reward: 1000,
            title_reward: Some("Truth Seeker".to_string()),
            category: AchievementCategory::Exploration,
        },
        AchievementDefinition {
            id: "cairn_5".to_string(),
            name: "Whispers of Stone".to_string(),
            description: "Discover 5 cairns".to_string(),
            icon: "🗿".to_string(),
            xp_reward: 100,
            title_reward: None,
            category: AchievementCategory::Exploration,
        },
        
        // Underwater/Diving themed (Bering Sea lore) - tiered progression
        AchievementDefinition {
            id: "coral_10".to_string(),
            name: "Shallow Diver".to_string(),
            description: "Mine coral 10 times".to_string(),
            icon: "🪸".to_string(),
            xp_reward: 50,
            title_reward: None,
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "coral_25".to_string(),
            name: "Reef Explorer".to_string(),
            description: "Mine coral 25 times".to_string(),
            icon: "🪸".to_string(),
            xp_reward: 100,
            title_reward: None,
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "coral_50".to_string(),
            name: "Deep Diver".to_string(),
            description: "Mine coral 50 times".to_string(),
            icon: "🤿".to_string(),
            xp_reward: 175,
            title_reward: Some("Deep Diver".to_string()),
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "coral_100".to_string(),
            name: "Bering's Child".to_string(),
            description: "Mine coral 100 times - master the frigid waters".to_string(),
            icon: "🌊".to_string(),
            xp_reward: 300,
            title_reward: Some("Bering's Child".to_string()),
            category: AchievementCategory::Collection,
        },
        
        // Gathering/Foraging themed (tiered progression)
        AchievementDefinition {
            id: "plants_50".to_string(),
            name: "Forager".to_string(),
            description: "Harvest 50 wild plants".to_string(),
            icon: "🌿".to_string(),
            xp_reward: 75,
            title_reward: None,
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "plants_100".to_string(),
            name: "Gatherer".to_string(),
            description: "Harvest 100 wild plants".to_string(),
            icon: "🌾".to_string(),
            xp_reward: 125,
            title_reward: None,
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "plants_250".to_string(),
            name: "Experienced Forager".to_string(),
            description: "Harvest 250 wild plants".to_string(),
            icon: "🌻".to_string(),
            xp_reward: 200,
            title_reward: Some("Experienced Forager".to_string()),
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "plants_500".to_string(),
            name: "Islander".to_string(),
            description: "Harvest 500 plants - live off the land like the Aleuts".to_string(),
            icon: "🏝️".to_string(),
            xp_reward: 400,
            title_reward: Some("Islander".to_string()),
            category: AchievementCategory::Collection,
        },
        
        // Plant Variety Achievements (unique types harvested)
        AchievementDefinition {
            id: "plant_types_5".to_string(),
            name: "Curious Forager".to_string(),
            description: "Harvest 5 different plant types".to_string(),
            icon: "🔍".to_string(),
            xp_reward: 50,
            title_reward: None,
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "plant_types_15".to_string(),
            name: "Amateur Botanist".to_string(),
            description: "Harvest 15 different plant types".to_string(),
            icon: "📚".to_string(),
            xp_reward: 150,
            title_reward: None,
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "plant_types_30".to_string(),
            name: "Experienced Botanist".to_string(),
            description: "Harvest 30 different plant types".to_string(),
            icon: "🎓".to_string(),
            xp_reward: 300,
            title_reward: Some("Experienced Botanist".to_string()),
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "plant_types_49".to_string(),
            name: "Master Botanist".to_string(),
            description: "Harvest all 49 plant types - a true expert of island flora!".to_string(),
            icon: "🏆".to_string(),
            xp_reward: 750,
            title_reward: Some("Master Botanist".to_string()),
            category: AchievementCategory::Collection,
        },
        
        // Category Completion Achievements
        AchievementDefinition {
            id: "berry_collector".to_string(),
            name: "Berry Picker".to_string(),
            description: "Harvest all 7 berry types - from lingonberries to cloudberries".to_string(),
            icon: "🫐".to_string(),
            xp_reward: 200,
            title_reward: Some("Berry Picker".to_string()),
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "mushroom_master".to_string(),
            name: "Mycologist".to_string(),
            description: "Harvest all 6 mushroom types - even the deadly ones!".to_string(),
            icon: "🍄".to_string(),
            xp_reward: 250,
            title_reward: Some("Mycologist".to_string()),
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "herb_master".to_string(),
            name: "Master Herbalist".to_string(),
            description: "Harvest all 9 herb types - from yarrow to ginseng".to_string(),
            icon: "🌿".to_string(),
            xp_reward: 300,
            title_reward: Some("Master Herbalist".to_string()),
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "toxic_expert".to_string(),
            name: "Toxicologist".to_string(),
            description: "Harvest all 5 toxic plants - brave and knowledgeable!".to_string(),
            icon: "☠️".to_string(),
            xp_reward: 350,
            title_reward: Some("Toxicologist".to_string()),
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "arctic_botanist".to_string(),
            name: "Arctic Explorer".to_string(),
            description: "Harvest all 6 arctic/alpine plant types".to_string(),
            icon: "❄️".to_string(),
            xp_reward: 300,
            title_reward: Some("Arctic Explorer".to_string()),
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "vegetable_farmer".to_string(),
            name: "Green Thumb".to_string(),
            description: "Harvest all 8 vegetable types - master the island's crops".to_string(),
            icon: "🥕".to_string(),
            xp_reward: 250,
            title_reward: Some("Green Thumb".to_string()),
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "fiber_gatherer".to_string(),
            name: "Fiber Expert".to_string(),
            description: "Harvest all 8 fiber plant types - essential for survival".to_string(),
            icon: "🧵".to_string(),
            xp_reward: 250,
            title_reward: Some("Fiber Expert".to_string()),
            category: AchievementCategory::Collection,
        },
        
        // Farming Achievements (seeds planted)
        AchievementDefinition {
            id: "farmer_10".to_string(),
            name: "Farmer".to_string(),
            description: "Plant 10 seeds - begin your farming journey".to_string(),
            icon: "🌱".to_string(),
            xp_reward: 50,
            title_reward: None,
            category: AchievementCategory::Crafting,
        },
        AchievementDefinition {
            id: "farmer_50".to_string(),
            name: "Dedicated Farmer".to_string(),
            description: "Plant 50 seeds".to_string(),
            icon: "🌾".to_string(),
            xp_reward: 125,
            title_reward: None,
            category: AchievementCategory::Crafting,
        },
        AchievementDefinition {
            id: "farmer_100".to_string(),
            name: "Agricultural Pioneer".to_string(),
            description: "Plant 100 seeds - taming the wild island".to_string(),
            icon: "🚜".to_string(),
            xp_reward: 250,
            title_reward: Some("Agricultural Pioneer".to_string()),
            category: AchievementCategory::Crafting,
        },
        AchievementDefinition {
            id: "farmer_250".to_string(),
            name: "Master Farmer".to_string(),
            description: "Plant 250 seeds - your farm feeds the compound".to_string(),
            icon: "🏡".to_string(),
            xp_reward: 500,
            title_reward: Some("Master Farmer".to_string()),
            category: AchievementCategory::Crafting,
        },
        
        // Combat themed (tiered progression)
        AchievementDefinition {
            id: "animals_10".to_string(),
            name: "Hunter".to_string(),
            description: "Kill 10 wild animals".to_string(),
            icon: "🏹".to_string(),
            xp_reward: 75,
            title_reward: None,
            category: AchievementCategory::Combat,
        },
        AchievementDefinition {
            id: "animals_25".to_string(),
            name: "Competent Hunter".to_string(),
            description: "Kill 25 wild animals".to_string(),
            icon: "🏹".to_string(),
            xp_reward: 125,
            title_reward: None,
            category: AchievementCategory::Combat,
        },
        AchievementDefinition {
            id: "animals_50".to_string(),
            name: "Skilled Hunter".to_string(),
            description: "Kill 50 wild animals".to_string(),
            icon: "🎯".to_string(),
            xp_reward: 200,
            title_reward: Some("Skilled Hunter".to_string()),
            category: AchievementCategory::Combat,
        },
        AchievementDefinition {
            id: "animals_100".to_string(),
            name: "Apex Predator".to_string(),
            description: "Kill 100 wild animals - dominate the food chain".to_string(),
            icon: "🐺".to_string(),
            xp_reward: 400,
            title_reward: Some("Apex Predator".to_string()),
            category: AchievementCategory::Combat,
        },
        
        // Resource gathering themed (volcanic island) - tiered progression
        AchievementDefinition {
            id: "trees_100".to_string(),
            name: "Woodcutter".to_string(),
            description: "Chop down 100 trees".to_string(),
            icon: "🪓".to_string(),
            xp_reward: 100,
            title_reward: None,
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "trees_250".to_string(),
            name: "Lumberjack".to_string(),
            description: "Chop down 250 trees".to_string(),
            icon: "🪓".to_string(),
            xp_reward: 175,
            title_reward: None,
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "trees_500".to_string(),
            name: "Forest Tamer".to_string(),
            description: "Chop down 500 trees".to_string(),
            icon: "🌲".to_string(),
            xp_reward: 300,
            title_reward: Some("Forest Tamer".to_string()),
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "trees_1000".to_string(),
            name: "Deforester".to_string(),
            description: "Chop down 1000 trees - reshape the landscape".to_string(),
            icon: "🌲".to_string(),
            xp_reward: 500,
            title_reward: Some("Deforester".to_string()),
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "stones_100".to_string(),
            name: "Quarrier".to_string(),
            description: "Mine 100 stone deposits".to_string(),
            icon: "⛏️".to_string(),
            xp_reward: 100,
            title_reward: None,
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "stones_250".to_string(),
            name: "Stone Mason".to_string(),
            description: "Mine 250 stone deposits".to_string(),
            icon: "⛏️".to_string(),
            xp_reward: 175,
            title_reward: None,
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "stones_500".to_string(),
            name: "Rock Breaker".to_string(),
            description: "Mine 500 stone deposits".to_string(),
            icon: "🪨".to_string(),
            xp_reward: 300,
            title_reward: Some("Rock Breaker".to_string()),
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "stones_1000".to_string(),
            name: "Volcanic Born".to_string(),
            description: "Mine 1000 stones - harness the island's ancient fire".to_string(),
            icon: "🌋".to_string(),
            xp_reward: 500,
            title_reward: Some("Volcanic Born".to_string()),
            category: AchievementCategory::Collection,
        },
        
        // Crafting themed - tiered progression
        AchievementDefinition {
            id: "crafted_50".to_string(),
            name: "Tinkerer".to_string(),
            description: "Craft 50 items".to_string(),
            icon: "🔧".to_string(),
            xp_reward: 75,
            title_reward: None,
            category: AchievementCategory::Crafting,
        },
        AchievementDefinition {
            id: "crafted_100".to_string(),
            name: "Crafter".to_string(),
            description: "Craft 100 items".to_string(),
            icon: "🔧".to_string(),
            xp_reward: 125,
            title_reward: None,
            category: AchievementCategory::Crafting,
        },
        AchievementDefinition {
            id: "crafted_250".to_string(),
            name: "Industrious".to_string(),
            description: "Craft 250 items".to_string(),
            icon: "🛠️".to_string(),
            xp_reward: 250,
            title_reward: Some("Industrious".to_string()),
            category: AchievementCategory::Crafting,
        },
        AchievementDefinition {
            id: "crafted_500".to_string(),
            name: "Master Craftsman".to_string(),
            description: "Craft 500 items - innovation through necessity".to_string(),
            icon: "⚒️".to_string(),
            xp_reward: 400,
            title_reward: Some("Master Craftsman".to_string()),
            category: AchievementCategory::Crafting,
        },
        
        // Survival streaks (ALK compound theme - "the loop")
        AchievementDefinition {
            id: "login_7".to_string(),
            name: "Routine".to_string(),
            description: "Log in for 7 consecutive days".to_string(),
            icon: "📅".to_string(),
            xp_reward: 200,
            title_reward: None,
            category: AchievementCategory::Social,
        },
        AchievementDefinition {
            id: "login_30".to_string(),
            name: "Institutionalized".to_string(),
            description: "Log in for 30 consecutive days - the compound is your home now".to_string(),
            icon: "🏛️".to_string(),
            xp_reward: 750,
            title_reward: Some("Institutionalized".to_string()),
            category: AchievementCategory::Social,
        },
        
        // Level achievements
        AchievementDefinition {
            id: "level_50".to_string(),
            name: "Seasoned".to_string(),
            description: "Reach level 50".to_string(),
            icon: "💎".to_string(),
            xp_reward: 1000,
            title_reward: Some("Seasoned".to_string()),
            category: AchievementCategory::Survival,
        },
        AchievementDefinition {
            id: "level_100".to_string(),
            name: "Legend of the Compound".to_string(),
            description: "Reach level 100 - transcend the system".to_string(),
            icon: "👑".to_string(),
            xp_reward: 2500,
            title_reward: Some("Legend".to_string()),
            category: AchievementCategory::Survival,
        },
        
        // Death-related (The Freeze lore) - tiered progression
        AchievementDefinition {
            id: "deaths_10".to_string(),
            name: "Resilient".to_string(),
            description: "Die 10 times and keep coming back".to_string(),
            icon: "🔄".to_string(),
            xp_reward: 100,
            title_reward: None,
            category: AchievementCategory::Survival,
        },
        AchievementDefinition {
            id: "deaths_50".to_string(),
            name: "Ghost".to_string(),
            description: "Die 50 times - death is just a reset in the compound".to_string(),
            icon: "👻".to_string(),
            xp_reward: 250,
            title_reward: Some("Ghost".to_string()),
            category: AchievementCategory::Survival,
        },
        AchievementDefinition {
            id: "deaths_100".to_string(),
            name: "Phoenix".to_string(),
            description: "Die 100 times - rise from the ashes, again and again".to_string(),
            icon: "🔥".to_string(),
            xp_reward: 500,
            title_reward: Some("Phoenix".to_string()),
            category: AchievementCategory::Survival,
        },
        
        // ALK Contracts themed (Directorate lore)
        AchievementDefinition {
            id: "contracts_100".to_string(),
            name: "Directorate Asset".to_string(),
            description: "Complete 100 ALK contracts - indispensable to the system".to_string(),
            icon: "🎖️".to_string(),
            xp_reward: 800,
            title_reward: Some("Directorate Asset".to_string()),
            category: AchievementCategory::Social,
        },
        
        // Shards themed (the mysterious currency)
        AchievementDefinition {
            id: "shards_1000".to_string(),
            name: "Shard Collector".to_string(),
            description: "Earn 1000 total shards".to_string(),
            icon: "💠".to_string(),
            xp_reward: 150,
            title_reward: None,
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "shards_10000".to_string(),
            name: "Shard Baron".to_string(),
            description: "Earn 10000 total shards - what are they really for?".to_string(),
            icon: "🔮".to_string(),
            xp_reward: 600,
            title_reward: Some("Shard Baron".to_string()),
            category: AchievementCategory::Collection,
        },
        
        // === "FIRST" MILESTONE ACHIEVEMENTS ===
        // Rewarding players for their first action in each category
        AchievementDefinition {
            id: "first_fish".to_string(),
            name: "First Catch".to_string(),
            description: "Catch your first fish".to_string(),
            icon: "🎣".to_string(),
            xp_reward: 10,
            title_reward: None,
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "first_kill".to_string(),
            name: "First Blood".to_string(),
            description: "Kill your first wild animal".to_string(),
            icon: "🩸".to_string(),
            xp_reward: 10,
            title_reward: None,
            category: AchievementCategory::Combat,
        },
        AchievementDefinition {
            id: "first_plant".to_string(),
            name: "First Harvest".to_string(),
            description: "Harvest your first wild plant".to_string(),
            icon: "🌿".to_string(),
            xp_reward: 10,
            title_reward: None,
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "first_tree".to_string(),
            name: "Timber!".to_string(),
            description: "Chop down your first tree".to_string(),
            icon: "🪓".to_string(),
            xp_reward: 10,
            title_reward: None,
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "first_stone".to_string(),
            name: "Rock Solid".to_string(),
            description: "Mine your first stone".to_string(),
            icon: "⛏️".to_string(),
            xp_reward: 10,
            title_reward: None,
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "first_seed".to_string(),
            name: "Green Beginnings".to_string(),
            description: "Plant your first seed".to_string(),
            icon: "🌱".to_string(),
            xp_reward: 10,
            title_reward: None,
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "first_craft".to_string(),
            name: "Maker".to_string(),
            description: "Craft your first item".to_string(),
            icon: "🔨".to_string(),
            xp_reward: 10,
            title_reward: None,
            category: AchievementCategory::Crafting,
        },
        AchievementDefinition {
            id: "first_coral".to_string(),
            name: "Deep Discovery".to_string(),
            description: "Mine your first coral".to_string(),
            icon: "🪸".to_string(),
            xp_reward: 10,
            title_reward: None,
            category: AchievementCategory::Collection,
        },
        AchievementDefinition {
            id: "first_brew".to_string(),
            name: "Alchemist".to_string(),
            description: "Complete your first brew".to_string(),
            icon: "⚗️".to_string(),
            xp_reward: 15,
            title_reward: None,
            category: AchievementCategory::Crafting,
        },
        AchievementDefinition {
            id: "first_barrel".to_string(),
            name: "Scavenger".to_string(),
            description: "Destroy your first supply barrel".to_string(),
            icon: "🛢️".to_string(),
            xp_reward: 15,
            title_reward: None,
            category: AchievementCategory::Exploration,
        },
        
        // === WEAPON-SPECIFIC KILL ACHIEVEMENTS ===
        // Bow achievements
        AchievementDefinition {
            id: "bow_kills_10".to_string(),
            name: "Bowman".to_string(),
            description: "Kill 10 animals with a bow".to_string(),
            icon: "🏹".to_string(),
            xp_reward: 75,
            title_reward: None,
            category: AchievementCategory::Combat,
        },
        AchievementDefinition {
            id: "bow_kills_50".to_string(),
            name: "Sharpshooter".to_string(),
            description: "Kill 50 animals with a bow".to_string(),
            icon: "🏹".to_string(),
            xp_reward: 200,
            title_reward: Some("Sharpshooter".to_string()),
            category: AchievementCategory::Combat,
        },
        AchievementDefinition {
            id: "bow_kills_100".to_string(),
            name: "Deadshot Archer".to_string(),
            description: "Kill 100 animals with a bow - master of the hunt".to_string(),
            icon: "🎯".to_string(),
            xp_reward: 400,
            title_reward: Some("Deadshot Archer".to_string()),
            category: AchievementCategory::Combat,
        },
        // Crossbow achievements
        AchievementDefinition {
            id: "crossbow_kills_10".to_string(),
            name: "Bolt Slinger".to_string(),
            description: "Kill 10 animals with a crossbow".to_string(),
            icon: "🎯".to_string(),
            xp_reward: 75,
            title_reward: None,
            category: AchievementCategory::Combat,
        },
        AchievementDefinition {
            id: "crossbow_kills_50".to_string(),
            name: "Crossbow Expert".to_string(),
            description: "Kill 50 animals with a crossbow".to_string(),
            icon: "⚔️".to_string(),
            xp_reward: 200,
            title_reward: Some("Crossbow Expert".to_string()),
            category: AchievementCategory::Combat,
        },
        AchievementDefinition {
            id: "crossbow_kills_100".to_string(),
            name: "Silent Death".to_string(),
            description: "Kill 100 animals with a crossbow - one shot, one kill".to_string(),
            icon: "💀".to_string(),
            xp_reward: 400,
            title_reward: Some("Silent Death".to_string()),
            category: AchievementCategory::Combat,
        },
        // Gun achievements
        AchievementDefinition {
            id: "gun_kills_10".to_string(),
            name: "Armed".to_string(),
            description: "Kill 10 animals with a firearm".to_string(),
            icon: "🔫".to_string(),
            xp_reward: 75,
            title_reward: None,
            category: AchievementCategory::Combat,
        },
        AchievementDefinition {
            id: "gun_kills_50".to_string(),
            name: "Gunslinger".to_string(),
            description: "Kill 50 animals with a firearm".to_string(),
            icon: "🔫".to_string(),
            xp_reward: 200,
            title_reward: Some("Gunslinger".to_string()),
            category: AchievementCategory::Combat,
        },
        AchievementDefinition {
            id: "gun_kills_100".to_string(),
            name: "Soviet Sharpshooter".to_string(),
            description: "Kill 100 animals with Soviet firearms - the motherland is proud".to_string(),
            icon: "☭".to_string(),
            xp_reward: 400,
            title_reward: Some("Soviet Sharpshooter".to_string()),
            category: AchievementCategory::Combat,
        },
        // Harpoon Gun achievements
        AchievementDefinition {
            id: "harpoon_gun_kills_10".to_string(),
            name: "Underwater Hunter".to_string(),
            description: "Kill 10 animals with the Reed Harpoon Gun".to_string(),
            icon: "🔱".to_string(),
            xp_reward: 100,
            title_reward: None,
            category: AchievementCategory::Combat,
        },
        AchievementDefinition {
            id: "harpoon_gun_kills_50".to_string(),
            name: "Aquatic Assassin".to_string(),
            description: "Kill 50 animals with the Reed Harpoon Gun".to_string(),
            icon: "🔱".to_string(),
            xp_reward: 200,
            title_reward: Some("Aquatic Assassin".to_string()),
            category: AchievementCategory::Combat,
        },
        AchievementDefinition {
            id: "harpoon_gun_kills_100".to_string(),
            name: "Poseidon's Wrath".to_string(),
            description: "Kill 100 animals with the Reed Harpoon Gun - master of underwater combat".to_string(),
            icon: "🌊".to_string(),
            xp_reward: 400,
            title_reward: Some("Poseidon's Wrath".to_string()),
            category: AchievementCategory::Combat,
        },
        // Melee achievements
        AchievementDefinition {
            id: "melee_kills_10".to_string(),
            name: "Up Close".to_string(),
            description: "Kill 10 animals with melee weapons".to_string(),
            icon: "⚔️".to_string(),
            xp_reward: 75,
            title_reward: None,
            category: AchievementCategory::Combat,
        },
        AchievementDefinition {
            id: "melee_kills_50".to_string(),
            name: "Brawler".to_string(),
            description: "Kill 50 animals with melee weapons".to_string(),
            icon: "🗡️".to_string(),
            xp_reward: 200,
            title_reward: Some("Brawler".to_string()),
            category: AchievementCategory::Combat,
        },
        AchievementDefinition {
            id: "melee_kills_100".to_string(),
            name: "Berserker".to_string(),
            description: "Kill 100 animals with melee weapons - embrace the chaos".to_string(),
            icon: "💪".to_string(),
            xp_reward: 400,
            title_reward: Some("Berserker".to_string()),
            category: AchievementCategory::Combat,
        },
        // Spear achievements
        AchievementDefinition {
            id: "spear_kills_25".to_string(),
            name: "Spearman".to_string(),
            description: "Kill 25 animals with spears".to_string(),
            icon: "🔱".to_string(),
            xp_reward: 125,
            title_reward: None,
            category: AchievementCategory::Combat,
        },
        AchievementDefinition {
            id: "spear_kills_100".to_string(),
            name: "Primal Hunter".to_string(),
            description: "Kill 100 animals with spears - like the ancient Aleut warriors".to_string(),
            icon: "🦣".to_string(),
            xp_reward: 350,
            title_reward: Some("Primal Hunter".to_string()),
            category: AchievementCategory::Combat,
        },
        
        // === TAMING ACHIEVEMENT (Specific) ===
        AchievementDefinition {
            id: "walrus_tamer".to_string(),
            name: "Walrus Whisperer".to_string(),
            description: "Tame an Arctic Walrus - a true bond with the Bering's most formidable beast".to_string(),
            icon: "🦭".to_string(),
            xp_reward: 500,
            title_reward: Some("Walrus Whisperer".to_string()),
            category: AchievementCategory::Survival,
        },
        
        // === BARREL ACHIEVEMENTS ===
        AchievementDefinition {
            id: "barrels_10".to_string(),
            name: "Looter".to_string(),
            description: "Destroy 10 supply barrels".to_string(),
            icon: "🛢️".to_string(),
            xp_reward: 50,
            title_reward: None,
            category: AchievementCategory::Exploration,
        },
        AchievementDefinition {
            id: "barrels_50".to_string(),
            name: "Treasure Hunter".to_string(),
            description: "Destroy 50 supply barrels".to_string(),
            icon: "💰".to_string(),
            xp_reward: 150,
            title_reward: Some("Treasure Hunter".to_string()),
            category: AchievementCategory::Exploration,
        },
        AchievementDefinition {
            id: "barrels_100".to_string(),
            name: "Soviet Salvager".to_string(),
            description: "Destroy 100 supply barrels - what did the ALK leave behind?".to_string(),
            icon: "📦".to_string(),
            xp_reward: 300,
            title_reward: Some("Soviet Salvager".to_string()),
            category: AchievementCategory::Exploration,
        },
        
        // === BREWING ACHIEVEMENTS ===
        AchievementDefinition {
            id: "brews_5".to_string(),
            name: "Apprentice Brewer".to_string(),
            description: "Complete 5 brews".to_string(),
            icon: "🍵".to_string(),
            xp_reward: 50,
            title_reward: None,
            category: AchievementCategory::Crafting,
        },
        AchievementDefinition {
            id: "brews_25".to_string(),
            name: "Cauldron Master".to_string(),
            description: "Complete 25 brews".to_string(),
            icon: "🫖".to_string(),
            xp_reward: 150,
            title_reward: Some("Cauldron Master".to_string()),
            category: AchievementCategory::Crafting,
        },
        AchievementDefinition {
            id: "brews_100".to_string(),
            name: "Grand Alchemist".to_string(),
            description: "Complete 100 brews - master of the Broth Pot".to_string(),
            icon: "⚗️".to_string(),
            xp_reward: 350,
            title_reward: Some("Grand Alchemist".to_string()),
            category: AchievementCategory::Crafting,
        },
        
        // === SHARD APPARITION / VOID MANIFESTATION ACHIEVEMENTS ===
        // Themed around the mysterious shard entities that manifest from the Void
        AchievementDefinition {
            id: "first_banishment".to_string(),
            name: "First Banishment".to_string(),
            description: "Banish your first Void Manifestation - they were never truly here".to_string(),
            icon: "👤".to_string(),
            xp_reward: 25,
            title_reward: None,
            category: AchievementCategory::Combat,
        },
        AchievementDefinition {
            id: "apparitions_10".to_string(),
            name: "Wraith Hunter".to_string(),
            description: "Banish 10 Void Manifestations".to_string(),
            icon: "👻".to_string(),
            xp_reward: 75,
            title_reward: None,
            category: AchievementCategory::Combat,
        },
        AchievementDefinition {
            id: "apparitions_25".to_string(),
            name: "Void Slayer".to_string(),
            description: "Banish 25 Void Manifestations - the shards fear you".to_string(),
            icon: "⚔️".to_string(),
            xp_reward: 150,
            title_reward: Some("Void Slayer".to_string()),
            category: AchievementCategory::Combat,
        },
        AchievementDefinition {
            id: "apparitions_50".to_string(),
            name: "Manifestation Purger".to_string(),
            description: "Banish 50 Void Manifestations - cleansing the island".to_string(),
            icon: "🌟".to_string(),
            xp_reward: 250,
            title_reward: Some("Purger".to_string()),
            category: AchievementCategory::Combat,
        },
        AchievementDefinition {
            id: "apparitions_100".to_string(),
            name: "Shard Exorcist".to_string(),
            description: "Banish 100 Void Manifestations - you understand their nature now".to_string(),
            icon: "✨".to_string(),
            xp_reward: 400,
            title_reward: Some("Shard Exorcist".to_string()),
            category: AchievementCategory::Combat,
        },
        AchievementDefinition {
            id: "apparitions_250".to_string(),
            name: "Void's Bane".to_string(),
            description: "Banish 250 Void Manifestations - the Entrainment recoils from you".to_string(),
            icon: "💠".to_string(),
            xp_reward: 600,
            title_reward: Some("Void's Bane".to_string()),
            category: AchievementCategory::Combat,
        },
        AchievementDefinition {
            id: "apparitions_500".to_string(),
            name: "The Banisher".to_string(),
            description: "Banish 500 Void Manifestations - SOVA cannot touch you".to_string(),
            icon: "🔥".to_string(),
            xp_reward: 1000,
            title_reward: Some("The Banisher".to_string()),
            category: AchievementCategory::Combat,
        },
        AchievementDefinition {
            id: "apparitions_1000".to_string(),
            name: "Void Annihilator".to_string(),
            description: "Banish 1000 Void Manifestations - you have become the island's guardian against the Entrainment".to_string(),
            icon: "👑".to_string(),
            xp_reward: 2000,
            title_reward: Some("Void Annihilator".to_string()),
            category: AchievementCategory::Combat,
        },
        
        // === VENOM SURVIVAL ACHIEVEMENTS (Cable Viper attacks cured with Anti-Venom) ===
        // Themed around surviving the deadly Cable Viper venom by using Anti-Venom
        AchievementDefinition {
            id: "first_venom_bite".to_string(),
            name: "First Sting".to_string(),
            description: "Cure your first Cable Viper bite with Anti-Venom - you live to fight another day".to_string(),
            icon: "🐍".to_string(),
            xp_reward: 25,
            title_reward: None,
            category: AchievementCategory::Survival,
        },
        AchievementDefinition {
            id: "venom_bites_5".to_string(),
            name: "Venom Survivor".to_string(),
            description: "Cure 5 Cable Viper bites - always keep Anti-Venom handy".to_string(),
            icon: "💉".to_string(),
            xp_reward: 75,
            title_reward: None,
            category: AchievementCategory::Survival,
        },
        AchievementDefinition {
            id: "venom_bites_10".to_string(),
            name: "Snake Charmer".to_string(),
            description: "Cure 10 Cable Viper bites - the vipers can't keep you down".to_string(),
            icon: "🐍".to_string(),
            xp_reward: 150,
            title_reward: Some("Snake Charmer".to_string()),
            category: AchievementCategory::Survival,
        },
        AchievementDefinition {
            id: "venom_bites_25".to_string(),
            name: "Venom Resistant".to_string(),
            description: "Cure 25 Cable Viper bites - you know the antidote by heart".to_string(),
            icon: "🛡️".to_string(),
            xp_reward: 300,
            title_reward: Some("Venom Resistant".to_string()),
            category: AchievementCategory::Survival,
        },
        AchievementDefinition {
            id: "venom_bites_50".to_string(),
            name: "Viper's Bane".to_string(),
            description: "Cure 50 Cable Viper bites - you've mastered survival against the deadliest snakes".to_string(),
            icon: "⚔️".to_string(),
            xp_reward: 500,
            title_reward: Some("Viper's Bane".to_string()),
            category: AchievementCategory::Survival,
        },
        
        // === INSANITY / SOVA ACHIEVEMENTS ===
        // Themed around the mysterious memory shard system and SOVA's whispers
        AchievementDefinition {
            id: "insanity_25".to_string(),
            name: "Whispers Begin".to_string(),
            description: "Reach 25% insanity - SOVA's first warning echoes in your mind".to_string(),
            icon: "👁️".to_string(),
            xp_reward: 25,
            title_reward: None,
            category: AchievementCategory::Survival,
        },
        AchievementDefinition {
            id: "insanity_50".to_string(),
            name: "Mind Unraveling".to_string(),
            description: "Reach 50% insanity - the voices grow louder, reality blurs".to_string(),
            icon: "🌀".to_string(),
            xp_reward: 50,
            title_reward: Some("Unstable".to_string()),
            category: AchievementCategory::Survival,
        },
        AchievementDefinition {
            id: "insanity_75".to_string(),
            name: "Edge of Oblivion".to_string(),
            description: "Reach 75% insanity - you stand at the precipice of the Void".to_string(),
            icon: "🕳️".to_string(),
            xp_reward: 75,
            title_reward: Some("Void-Touched".to_string()),
            category: AchievementCategory::Survival,
        },
        AchievementDefinition {
            id: "insanity_90".to_string(),
            name: "Void's Embrace".to_string(),
            description: "Reach 90% insanity - SOVA screams, reality fractures".to_string(),
            icon: "💀".to_string(),
            xp_reward: 100,
            title_reward: Some("Void-Walker".to_string()),
            category: AchievementCategory::Survival,
        },
        AchievementDefinition {
            id: "insanity_100".to_string(),
            name: "Entrained".to_string(),
            description: "Reach 100% insanity - you have become one with the Entrainment".to_string(),
            icon: "☠️".to_string(),
            xp_reward: 200,
            title_reward: Some("Entrained".to_string()),
            category: AchievementCategory::Survival,
        },
        AchievementDefinition {
            id: "entrainment_5".to_string(),
            name: "Familiar Darkness".to_string(),
            description: "Experience Entrainment 5 times - the Void knows your name".to_string(),
            icon: "🔮".to_string(),
            xp_reward: 150,
            title_reward: Some("Void Addict".to_string()),
            category: AchievementCategory::Survival,
        },
        AchievementDefinition {
            id: "entrainment_10".to_string(),
            name: "Beyond Redemption".to_string(),
            description: "Experience Entrainment 10 times - is there anything left of you?".to_string(),
            icon: "👻".to_string(),
            xp_reward: 300,
            title_reward: Some("Hollow One".to_string()),
            category: AchievementCategory::Survival,
        },
        AchievementDefinition {
            id: "entrainment_25".to_string(),
            name: "SOVA's Favorite".to_string(),
            description: "Experience Entrainment 25 times - she speaks to you now, always".to_string(),
            icon: "🎭".to_string(),
            xp_reward: 500,
            title_reward: Some("SOVA's Vessel".to_string()),
            category: AchievementCategory::Survival,
        },
    ];
    
    for achievement in achievements {
        achievement_table.insert(achievement);
    }
    
    log::info!("Seeded {} achievement definitions", achievement_table.iter().count());
    Ok(())
}

/// Initialize daily login rewards (called in init_module)
pub fn seed_daily_login_rewards(ctx: &ReducerContext) -> Result<(), String> {
    let reward_table = ctx.db.daily_login_reward();
    
    // Check if already seeded
    if reward_table.iter().count() > 0 {
        log::debug!("Daily login rewards already seeded");
        return Ok(());
    }
    
    let rewards = vec![
        DailyLoginReward { day: 1, shard_reward: 10, bonus_xp: 25 },
        DailyLoginReward { day: 2, shard_reward: 15, bonus_xp: 50 },
        DailyLoginReward { day: 3, shard_reward: 25, bonus_xp: 75 },
        DailyLoginReward { day: 4, shard_reward: 35, bonus_xp: 100 },
        DailyLoginReward { day: 5, shard_reward: 50, bonus_xp: 150 },
        DailyLoginReward { day: 6, shard_reward: 75, bonus_xp: 200 },
        DailyLoginReward { day: 7, shard_reward: 150, bonus_xp: 500 },
    ];
    
    for reward in rewards {
        reward_table.insert(reward);
    }
    
    log::info!("Seeded daily login rewards");
    Ok(())
}

// ============================================================================
// REDUCERS
// ============================================================================

/// Set active title for a player
#[spacetimedb::reducer]
pub fn set_active_title(ctx: &ReducerContext, title_id: Option<String>) -> Result<(), String> {
    let player_id = ctx.sender;
    let stats_table = ctx.db.player_stats();
    
    // Verify player has unlocked this title (check achievements)
    if let Some(ref title) = title_id {
        let has_title = ctx.db.player_achievement()
            .idx_player_achievements()
            .filter(&player_id)
            .any(|a| {
                if let Some(achievement) = ctx.db.achievement_definition().id().find(&a.achievement_id) {
                    achievement.title_reward.as_ref() == Some(title)
                } else {
                    false
                }
            });
        
        if !has_title {
            return Err(format!("You haven't unlocked the title '{}'", title));
        }
    }
    
    let mut stats = get_or_init_player_stats(ctx, player_id);
    stats.active_title_id = title_id.clone();
    stats.updated_at = ctx.timestamp;
    stats_table.player_id().update(stats);
    
    log::info!("Player {} set active title to {:?}", player_id, title_id);
    Ok(())
}

/// Get leaderboard for a category
#[spacetimedb::reducer]
pub fn get_leaderboard(ctx: &ReducerContext, category: LeaderboardCategory, limit: u32) -> Result<(), String> {
    let stats_table = ctx.db.player_stats();
    let players_table = ctx.db.player();
    let leaderboard_table = ctx.db.leaderboard_entry();
    
    // Clear old entries for this category
    let old_entries: Vec<_> = leaderboard_table
        .iter()
        .filter(|e| e.category == category)
        .collect();
    for entry in old_entries {
        leaderboard_table.id().delete(entry.id);
    }
    
    // Get all stats and sort by category
    let mut entries: Vec<(Identity, u64, String)> = Vec::new();
    
    for stats in stats_table.iter() {
        if let Some(player) = players_table.identity().find(&stats.player_id) {
            let value = match category {
                LeaderboardCategory::ShardsEarned => stats.total_shards_earned as u64,
                LeaderboardCategory::LongestSurvival => stats.longest_survival_seconds,
                LeaderboardCategory::ContractsCompleted => stats.contracts_completed as u64,
                LeaderboardCategory::FishCaught => stats.fish_caught as u64,
                LeaderboardCategory::CairnsDiscovered => stats.cairns_discovered as u64,
                LeaderboardCategory::Level => stats.level as u64,
            };
            
            entries.push((stats.player_id, value, player.username.clone()));
        }
    }
    
    // Sort descending
    entries.sort_by(|a, b| b.1.cmp(&a.1));
    
    // Create leaderboard entries
    for (rank, (player_id, value, username)) in entries.iter().enumerate().take(limit as usize) {
        let entry = LeaderboardEntry {
            id: 0,
            category: category.clone(),
            rank: (rank + 1) as u32,
            player_id: *player_id,
            player_username: username.clone(),
            value: *value,
            updated_at: ctx.timestamp,
        };
        leaderboard_table.insert(entry);
    }
    
    log::info!("Generated leaderboard for {:?} with {} entries", category, entries.len().min(limit as usize));
    Ok(())
}

